# Generated by Django 3.2.7 on 2021-09-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_auto_20210909_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='added_on',
            field=models.DateTimeField(),
        ),
    ]
