# Generated by Django 3.2.7 on 2021-11-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_user_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
    ]
