# Generated by Django 3.2.7 on 2021-09-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_alter_task_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
