# Generated by Django 3.2.7 on 2021-09-09 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_auto_20210909_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='domain_name',
            new_name='programming_language',
        ),
    ]
