# Generated by Django 3.2.7 on 2021-09-13 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0007_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='programming_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskapp.programminglanguage'),
        ),
    ]
