# Generated by Django 3.2.7 on 2021-09-13 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0009_tasktype_for_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='system_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(choices=[('Computer', 'Computer'), ('Laptop', 'Laptop'), ('Macbook', 'MacBook')], max_length=255)),
                ('specification', models.TextField()),
                ('system_service', models.TextField()),
                ('system_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskapp.user')),
            ],
        ),
    ]
