# Generated by Django 3.2.7 on 2021-09-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0010_system_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='system_info',
        ),
    ]
