# Generated by Django 3.2.7 on 2021-09-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0012_system_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_info',
            name='system_service',
            field=models.TextField(blank=True, null=True),
        ),
    ]
