# Generated by Django 3.2.7 on 2021-09-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0013_alter_system_info_system_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='system_info',
        ),
    ]
