# Generated by Django 3.2.7 on 2021-09-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0014_delete_system_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='system_info',
            fields=[
                ('system_type', models.CharField(choices=[('Computer', 'Computer'), ('Laptop', 'Laptop'), ('Macbook', 'MacBook')], max_length=255)),
                ('specification', models.TextField()),
                ('system_service', models.TextField(blank=True, null=True)),
                ('system_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
