# Generated by Django 3.2.7 on 2021-09-13 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0015_system_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='system_info',
            new_name='system_detail',
        ),
        migrations.CreateModel(
            name='Assigned_System_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_type', models.CharField(choices=[('Temporary', 'Temporary'), ('Permanent', 'Permanent')], max_length=255)),
                ('assigned_on', models.DateTimeField()),
                ('returned_on', models.DateTimeField(blank=True, null=True)),
                ('system_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taskapp.system_detail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taskapp.user')),
            ],
        ),
    ]
