# Generated by Django 3.2.7 on 2021-09-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0016_auto_20210913_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_detail',
            name='added_on',
            field=models.DateTimeField(),
        ),
    ]
