# Generated by Django 3.2.7 on 2021-09-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0017_alter_system_detail_added_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assigned_system_detail',
            options={'verbose_name': 'Assigned System Detail'},
        ),
        migrations.AlterModelOptions(
            name='programminglanguage',
            options={'verbose_name': 'Languages / Department'},
        ),
        migrations.AlterModelOptions(
            name='system_detail',
            options={'verbose_name': 'System Detail'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task'},
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={'verbose_name': 'Task Type'},
        ),
        migrations.AddField(
            model_name='user',
            name='office_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
