# Generated by Django 3.2.7 on 2021-10-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0018_auto_20210913_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
