# Generated by Django 3.2.7 on 2021-10-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0020_auto_20211001_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
