# Generated by Django 3.2.7 on 2021-10-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0021_auto_20211001_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
