# Generated by Django 3.2.7 on 2021-10-13 10:07

from django.db import migrations, models
import taskapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0023_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_pic',
            field=models.ImageField(blank=True, null=True, upload_to=taskapp.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_updated',
            field=models.BooleanField(default=False),
        ),
    ]
