# Generated by Django 3.2.7 on 2021-10-14 05:58

from django.db import migrations, models
import django.db.models.deletion
import taskapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0024_auto_20211013_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_uploaded_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to=taskapp.models.get_upload_files_path)),
                ('extension', models.CharField(max_length=255)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskapp.task')),
            ],
        ),
    ]
