# Generated by Django 3.2.7 on 2022-02-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0026_rename_puch_in_attendence_punch_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='attend_date',
            field=models.DateField(),
        ),
    ]
