# Generated by Django 3.2.7 on 2022-02-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0027_alter_attendence_attend_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='user',
        ),
    ]
