# Generated by Django 3.2.7 on 2022-02-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0028_remove_attendence_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendence',
        ),
    ]
