# Generated by Django 3.2.7 on 2022-02-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0029_delete_attendence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=30)),
                ('attend_date', models.DateField()),
                ('punch_in', models.DateTimeField()),
                ('punch_out', models.DateTimeField()),
                ('working_hours', models.CharField(max_length=2)),
            ],
        ),
    ]
