# Generated by Django 3.2.7 on 2022-02-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0031_alter_attendence_attend_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='punch_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='punch_out',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
