# Generated by Django 3.2.7 on 2022-02-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0032_auto_20220203_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='attend_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='punch_in',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='punch_out',
            field=models.TimeField(),
        ),
    ]
