# Generated by Django 3.2.7 on 2022-02-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0033_auto_20220203_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='punch_out',
            field=models.TimeField(default=''),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='working_hours',
            field=models.CharField(default='', max_length=2),
        ),
    ]
