# Generated by Django 3.2.7 on 2022-02-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0034_auto_20220203_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='attend_date',
            field=models.DateField(default=''),
        ),
    ]
