# Generated by Django 3.2.7 on 2022-02-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0040_alter_attendence_punch_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='punch_in',
            field=models.TimeField(),
        ),
    ]
