# Generated by Django 3.2.7 on 2022-02-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0043_alter_attendence_punch_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='punch_out',
            field=models.TimeField(),
        ),
    ]
