# Generated by Django 3.2.7 on 2022-02-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0045_alter_attendence_punch_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='punch_in',
            field=models.TimeField(),
        ),
    ]
