# Generated by Django 3.2.7 on 2022-06-14 06:48

from django.db import migrations, models
import taskapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0046_auto_20220614_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=taskapp.models.get_upload_display_profile_path),
        ),
    ]
