# Generated by Django 3.2.7 on 2022-02-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0049_alter_attendence_punch_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='presence',
            field=models.BooleanField(default=False),
        ),
    ]
