# Generated by Django 3.2.7 on 2022-02-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0050_attendence_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='presence',
            field=models.BooleanField(default=False),
        ),
    ]
