# Generated by Django 3.2.7 on 2022-02-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0051_user_presence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='person',
        ),
    ]
