# Generated by Django 3.2.7 on 2022-02-08 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0052_remove_attendence_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskapp.user'),
        ),
    ]
