# Generated by Django 3.2.7 on 2022-02-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0053_attendence_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='punch_in',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
